.\"
.\" "$Id$"
.\"
.\"   rastertoescpx man page for the CUPS Driver Development Kit.
.\"
.\"   Copyright 2007-2008 by Apple Inc.
.\"   Copyright 1997-2007 by Easy Software Products.
.\"
.\"   These coded instructions, statements, and computer programs are the
.\"   property of Apple Inc. and are protected by Federal copyright
.\"   law.  Distribution and use rights are outlined in the file "LICENSE.txt"
.\"   which should have been included with this file.  If this file is
.\"   file is missing or damaged, see the license at "http://www.cups.org/".
.\"
.TH rastertoescpx 1 "CUPS Driver Development Kit" "14 February 2007" "Apple Inc."
.SH NAME
rastertoescpx \- enhanced esc/p raster driver for cups
.SH SYNOPSIS
.B rastertoescpx
jobid user title copies options [
.I filename.ras
]
.SH DESCRIPTION
\fIrastertoescpx\fR converts a CUPS raster stream to ESC/P or
ESC/P2. It is used to support printing to a variety of EPSON and
EPSON-compatible printers and plotters.
.SH SEE ALSO
cupsprofile(1), ppdc(1), ppdhtml(1), ppdi(1), ppdmerge(1), ppdpo(1), ppdcfile(5), CUPS Driver Developer Kit Manual.
.SH COPYRIGHT
Copyright 2007-2008 by Apple Inc.
.\"
.\" End of "$Id$".
.\"
