.\"
.\" "$Id: cupstestdsc.man 7600 2008-05-20 21:06:23Z mike $"
.\"
.\"   cupstestdsc man page for CUPS.
.\"
.\"   Copyright 2007-2013 by Apple Inc.
.\"   Copyright 2006 by Easy Software Products.
.\"
.\"   These coded instructions, statements, and computer programs are the
.\"   property of Apple Inc. and are protected by Federal copyright
.\"   law.  Distribution and use rights are outlined in the file "LICENSE.txt"
.\"   which should have been included with this file.  If this file is
.\"   file is missing or damaged, see the license at "http://www.cups.org/".
.\"
.TH cupstestdsc 1 "CUPS" "20 March 2006" "Apple Inc."
.SH NAME
cupstestdsc \- test conformance of postscript files
.SH SYNOPSIS
.B cupstestdsc
[ -h ] filename.ps [ ...
.I filenameN.ps
]
.br
.B cupstestdsc
[ -h ] -
.SH DESCRIPTION
\fIcupstestdsc\fR tests the conformance of PostScript files to
the Adobe PostScript Language Document Structuring Conventions
Specification version 3.0. The results of testing and any other
output are sent to the standard output. The second form of the
command reads PostScript from the standard input.
.SH LIMITATIONS
\fIcupstestdsc\fR only validates the DSC comments in a PostScript
file and does not attempt to validate the PostScript code itself.
Developers must ensure that the PostScript they generate follows
the rules defined by Adobe. Specifically, all pages must be
independent of each other, code outside page descriptions may not
affect the graphics state (current font, color, transform matrix,
etc.), and device-specific commands such as setpagedevice should
not be used.
.SH SEE ALSO
http://localhost:631/help
.br
Adobe PostScript Language Document Structuring Conventions
Specification, Version 3.0.
.SH COPYRIGHT
Copyright 2007-2013 by Apple Inc.
.\"
.\" End of "$Id: cupstestdsc.man 7600 2008-05-20 21:06:23Z mike $".
.\"
