.\"
.\" "$Id: cups-polld.man 9771 2011-05-12 05:21:56Z mike $"
.\"
.\"   cups-polld man page for CUPS.
.\"
.\"   Copyright 2007-2011 by Apple Inc.
.\"   Copyright 1997-2006 by Easy Software Products.
.\"
.\"   These coded instructions, statements, and computer programs are the
.\"   property of Apple Inc. and are protected by Federal copyright
.\"   law.  Distribution and use rights are outlined in the file "LICENSE.txt"
.\"   which should have been included with this file.  If this file is
.\"   file is missing or damaged, see the license at "http://www.cups.org/".
.\"
.TH cups-polld 8 "CUPS" "12 February 2006" "Apple Inc."
.SH NAME
cups-polld \- cups printer polling daemon
.SH SYNOPSIS
.B cups-polld
.I address ipp-port interval browse-port
.SH DESCRIPTION
\fIcups-polld\fR polls remote servers for a list of available
printers and printer classes every \fIinterval\fR seconds.
Printer and class information is then broadcast to the localhost
interface (127.0.0.1) on the specified browse port for reception
by \fIcupsd(8)\fR.
.PP
This program is started automatically by \fIcupsd\fR for every
\fIBrowsePoll\fR directive found in the \fIcupsd.conf(5)\fR file.
.SH SEE ALSO
\fIcupsd(8)\fR, \fIcupsd.conf(5)\fR,
.br
http://localhost:631/help
.SH COPYRIGHT
Copyright 2007-2011 by Apple Inc.
.\"
.\" End of "$Id: cups-polld.man 9771 2011-05-12 05:21:56Z mike $".
.\"
