.\"
.\" "$Id$"
.\"
.\"   lpmove man page for the Common UNIX Printing System (CUPS).
.\"
.\"   Copyright 1997-2006 by Easy Software Products.
.\"
.\"   These coded instructions, statements, and computer programs are the
.\"   property of Easy Software Products and are protected by Federal
.\"   copyright law.  Distribution and use rights are outlined in the file
.\"   "LICENSE.txt" which should have been included with this file.  If this
.\"   file is missing or damaged please contact Easy Software Products
.\"   at:
.\"
.\"       Attn: CUPS Licensing Information
.\"       Easy Software Products
.\"       44141 Airport View Drive, Suite 204
.\"       Hollywood, Maryland 20636 USA
.\"
.\"       Voice: (301) 373-9600
.\"       EMail: cups-info@cups.org
.\"         WWW: http://www.cups.org
.\"
.TH lpmove 8 "Common UNIX Printing System" "18 January 2006" "Easy Software Products"
.SH NAME
lpmove \- move a job or all jobs to a new destination
.SH SYNOPSIS
.B lpmove
[ -E ] [ -h
.I server
]
.I job destination
.br
.B lpmove
[ -E ] [ -h
.I server
]
.I source destination
.SH DESCRIPTION
\fBlpmove\fR moves the specified \fIjob\fR or all jobs from
\fIsource\fR to \fIdestination\fR. \fIjob\fR can be the job ID
number or the old destination and job ID:
.br
.nf

     lpmove 123 newprinter
     lpmove oldprinter-123 newprinter
.fi
.SH OPTIONS
The \fI-E\fR option forces encryption when connecting to the server.
.LP
The \fI-h\fR option specifies an alternate server.
.SH SEE ALSO
cancel(1), lp(1)
.br
http://localhost:631/help
.SH COPYRIGHT
Copyright 1993-2006 by Easy Software Products, All Rights Reserved.
.\"
.\" End of "$Id$".
.\"
