.\"
.\" "$Id: lpq.man,v 1.2 2000/07/20 17:10:57 mike Exp $"
.\"
.\"   lpq man page for the Common UNIX Printing System (CUPS).
.\"
.\"   Copyright 1997-2000 by Easy Software Products.
.\"
.\"   These coded instructions, statements, and computer programs are the
.\"   property of Easy Software Products and are protected by Federal
.\"   copyright law.  Distribution and use rights are outlined in the file
.\"   "LICENSE.txt" which should have been included with this file.  If this
.\"   file is missing or damaged please contact Easy Software Products
.\"   at:
.\"
.\"       Attn: CUPS Licensing Information
.\"       Easy Software Products
.\"       44141 Airport View Drive, Suite 204
.\"       Hollywood, Maryland 20636-3111 USA
.\"
.\"       Voice: (301) 373-9603
.\"       EMail: cups-info@cups.org
.\"         WWW: http://www.cups.org
.\"
.TH lpq 1 "Common UNIX Printing System" "7 December 1999" "Easy Software Products"
.SH NAME
lpq \- show printer queue status
.SH SYNOPSIS
.B lpq
[ \-P
.I dest
] [ \-l ] [
.I +interval
]
.SH DESCRIPTION
\fIlpq\fR shows the current print queue status on the named printer.
Jobs queued on the default destination will be shown if no printer or
class is specified on the command-line.
.LP
The \fIinterval\fR option allows you to continuously report the jobs
in the queue until the queue is empty; the list of jobs is show one
every \fIinterval\fR seconds.
.LP
The \fI-l\fR option requests a more verbose reporting format.
.SH SEE ALSO
cancel(1), lp(1), lpr(1), lprm(1), lpstat(1)
.br
CUPS Software Users Manual,
http://localhost:631/documentation.html
.SH COPYRIGHT
Copyright 1993-2000 by Easy Software Products, All Rights Reserved.
.\"
.\" End of "$Id: lpq.man,v 1.2 2000/07/20 17:10:57 mike Exp $".
.\"
