.\" 
.\" "$Id: cups-polld.man,v 1.1 2004/10/20 18:00:54 mike Exp $"
.\" 
.\" cups-polld man page for the Common UNIX Printing System (CUPS).
.\" 
.\" Copyright 1997-2004 by Easy Software Products.
.\" 
.\" These coded instructions, statements, and computer programs are the
.\" property of Easy Software Products and are protected by Federal
.\" copyright law.  Distribution and use rights are outlined in the file
.\" "LICENSE.txt" which should have been included with this file.  If this
.\" file is missing or damaged please contact Easy Software Products
.\" at:
.\" 
.\" Attn: CUPS Licensing Information
.\" Easy Software Products
.\" 44141 Airport View Drive, Suite 204
.\" Hollywood, Maryland 20636-3142 USA
.\" 
.\" Voice: (301) 373-9600
.\" EMail: cups-info@cups.org
.\" WWW: http://www.cups.org
.\" 
.TH "cups-polld" "8" "Common UNIX Printing System" "10 de Mayo de 2000" "Easy Software Products"
.SH "NOMBRE"
cups\-polld \- demonio de interrogación de impresoras cups
.SH "SINOPSIS"
.B cups\-polld
.I dirección puerto\-ipp intervalo puerto\-navegación
.SH "DESCRIPCIÓN"
\fBcups\-polld\fR interroga a los servidores remotos por la lista de impresoras y clases de impresora disponibles cada \fIintervalo\fR segundos. La información sobre las impresoras y las clases es entonces reenviada a la interfaz localhost (127.0.0.1)
para que sea recibida por \fBcupsd(8)\fR.
.PP 
Este programa es arrancado automáticamente por \fBcupsd\fR para cada una de las directivas BrowsePoll encontradas en al archivo \fBcupsd.conf\fR.
.SH "VÉASE TAMBIÉN"
cupsd.conf(5),
Manual de administrador de CUPS,
http://localhost:631/documentation.html
.SH "DERECHOS DE COPIA"
Los derechos de copia 1993\-2004 son de Easy Software Products. Todos los derechos reservados.

.SH "TRADUCCIÓN"
Juan Pablo González Riopedre <riopedre@tiscali.es>
.\"
.\" End of "$Id: cups-polld.man,v 1.1 2004/10/20 18:00:54 mike Exp $".
.\"
