.\"
.\" "$Id: cups-config.man,v 1.1 2002/05/21 19:59:42 mike Exp $"
.\"
.\"   cups-config man page for the Common UNIX Printing System (CUPS).
.\"
.\"   Copyright 1997-2002 by Easy Software Products.
.\"
.\"   These coded instructions, statements, and computer programs are the
.\"   property of Easy Software Products and are protected by Federal
.\"   copyright law.  Distribution and use rights are outlined in the file
.\"   "LICENSE.txt" which should have been included with this file.  If this
.\"   file is missing or damaged please contact Easy Software Products
.\"   at:
.\"
.\"       Attn: CUPS Licensing Information
.\"       Easy Software Products
.\"       44141 Airport View Drive, Suite 204
.\"       Hollywood, Maryland 20636-3111 USA
.\"
.\"       Voice: (301) 373-9603
.\"       EMail: cups-info@cups.org
.\"         WWW: http://www.cups.org
.\"
.TH cups-config 3 "Common UNIX Printing System" "25 Octobre 2001" "Easy Software Products"
.SH NOM
cups-config \- Récupère les informations concernant les API, la compilation, les répertoires et les liens de CUPS
.SH SYNOPSIS
.B cups-config
--api-version
.br
.B cups-config
--cflags
.br
.B cups-config
--datadir
.br
.B cups-config
--help
.br
.B cups-config
--ldflags
.br
.B cups-config
[
.I --image
] [
.I --static
] --libs
.br
.B cups-config
--serverbin
.br
.B cups-config
--serverroot
.br
.B cups-config
--version
.br
.SH DESCRIPTION
\fBcups-config\fR est le programme visualisation de la configuration de CUPS. Il doit être
utilisé par les développeurs pour déterminer les options du compilateur et du linkeur,
ainsi que l'endroit où ont été installés les filtres,
fichiers de configuration et pilotes.
.LP
La commande \fI--api-version\fR affiche la version de l'API (majeur.mineur).
.LP
La commande \fI--cflags\fR affiche les options indispensables de compilation.
.LP
La commande \fI--datadir\fR affiche le répertoire par défaut des données CUPS.
.LP
La commande \fI--help\fR affiche le message d'utilisation de ce programme.
.LP
La commande \fI--ldflags\fR affiche les options indispensables pour l'édition des liens.
.LP
La commande \fI--libs\fR affiche les bibliothèques nécessaires pour l'édition des liens.
L'option \fI--image\fR ajoute à la liste les bibliothèque pour les images.
L'option \fI--static\fR affiche les bibliothèques statiques au lieu des bibliothèques
dynamiques.
.LP
La commande \fI--serverbin\fR affiche le répertoire par défaut où
les programmes de filtres et backends CUPS sont stockés.
.LP
La commande \fI--serverroot\fR affiche le fichier de configuration par défaut de CUPS.
.LP
La commande \fI--version\fR affiche le numéro complet de version de CUPS
(majeur.mineur.révision).
.SH VOIR AUSSI
CUPS Software Programmers Manual,
http://localhost:631/documentation.html
.SH COPYRIGHT
Copyright 1993-2002 Easy Software Products, Tous droits réservés.
.SH TRADUCTION
Gilles QUERRET <gilles.querret@nerim.net>
.\"
.\" End of "$Id: cups-config.man,v 1.1 2002/05/21 19:59:42 mike Exp $".
.\"


