.\"
.\" "$Id: cups-polld.man,v 1.1.2.1 2002/05/21 20:05:49 mike Exp $"
.\"
.\"   cups-polld man page for the Common UNIX Printing System (CUPS).
.\"
.\"   Copyright 1997-2002 by Easy Software Products.
.\"
.\"   These coded instructions, statements, and computer programs are the
.\"   property of Easy Software Products and are protected by Federal
.\"   copyright law.  Distribution and use rights are outlined in the file
.\"   "LICENSE.txt" which should have been included with this file.  If this
.\"   file is missing or damaged please contact Easy Software Products
.\"   at:
.\"
.\"       Attn: CUPS Licensing Information
.\"       Easy Software Products
.\"       44141 Airport View Drive, Suite 204
.\"       Hollywood, Maryland 20636-3111 USA
.\"
.\"       Voice: (301) 373-9603
.\"       EMail: cups-info@cups.org
.\"         WWW: http://www.cups.org
.\"
.TH cups-polld 8 "Common UNIX Printing System" "10 Mai 2000" "Easy Software Products"
.SH NOM
cups-polld \- Démon d'interrogation des imprimantes CUPS
.SH SYNOPSIS
.B cups-polld
.I adresse port-ipp intervalle port-de-navigation
.SH DESCRIPTION
\fBcups-polld\fR interroge des serveurs distants afin d'obtenir la
liste des imprimantes et classes d'imprimantes disponibles toutes
les \fIintervalle\fR secondes. Les informations sont alors renvoyées
vers l'interface locale (127.0.0.1) pour être récupérées par \fBcupsd(8)\fR.
.PP
Ce programme est démarré automatiquement par \fBcupsd\fR pour chaque
directive «\ BrowsePoll\ » trouvée dans le fichier \fBcupsd.conf\fR.
.SH VOIR AUSSI
cupsd.conf(5),
CUPS Software Administrators Manual,
http://localhost:631/documentation.html
.SH COPYRIGHT
Copyright 1993-2002 Easy Software Products, Tous droits réservés.
.SH TRADUCTION
Gilles QUERRET <gilles.querret@nerim.net>
.\"
.\" End of "$Id: cups-polld.man,v 1.1.2.1 2002/05/21 20:05:49 mike Exp $".
.\"

