.\"
.\" "$Id: cupsd.man,v 1.1.2.1 2002/05/21 20:05:50 mike Exp $"
.\"
.\"   cupsd man page for the Common UNIX Printing System (CUPS).
.\"
.\"   Copyright 1997-2001 by Easy Software Products.
.\"
.\"   These coded instructions, statements, and computer programs are the
.\"   property of Easy Software Products and are protected by Federal
.\"   copyright law.  Distribution and use rights are outlined in the file
.\"   "LICENSE.txt" which should have been included with this file.  If this
.\"   file is missing or damaged please contact Easy Software Products
.\"   at:
.\"
.\"       Attn: CUPS Licensing Information
.\"       Easy Software Products
.\"       44141 Airport View Drive, Suite 204
.\"       Hollywood, Maryland 20636-3111 USA
.\"
.\"       Voice: (301) 373-9603
.\"       EMail: cups-info@cups.org
.\"         WWW: http://www.cups.org
.\"
.TH cupsd 8 "Common UNIX Printing System" "19 Octobre 2000" "Easy Software Products"
.SH NOM
cupsd \- common unix printing system daemon
.SH SYNOPSIS
.B cupsd
[ \-c
.I config-file
] [ \-f ]
.SH DESCRIPTION
\fIcupsd\fR est un programmateur pour le système Common UNIX Printing System. Il fournit des outils pour un système d'impression de base sous le Internet Printing Protocol, version 1.1. Si aucune option n'est spécifiée dans la ligne de commande, alors le fichier de configuration par défaut (habituellement \fI/etc/cups/cupsd.conf\fR) sera utilisé.
.PP
L'option \fI-f\fR force \fIcupsd\fR à tourner en avant-plan\ ; par défaut, cupsd tourne en arrière-plan comme «\ démon\ ».
.SH COMPATIBILITÉ
\fIcupsd\fR fournit tous les attributs et opération de IPP/1.1. Il implémente aussi plusieurs opérations d'administration spécifiques à CUPS
.SH VOIR AUSSI
backend(1), classes.conf(5), cupsd.conf(5), filter(1), mime.convs(5),
mime.types(5), printers.conf(5),
CUPS Implementation of IPP,
CUPS Interface Design Description,
CUPS Software Administrators Manual,
http://localhost:631/documentation.html
.SH COPYRIGHT
Copyright 1993-2001 by Easy Software Products, All Rights Reserved.
.\"
.\" End of "$Id: cupsd.man,v 1.1.2.1 2002/05/21 20:05:50 mike Exp $".
.\"
