queries:
  - exclude: cpp/integer-multiplication-cast-to-long
  - exclude: cpp/missing-header-guard
  - exclude: cpp/short-global-name
  - exclude: cpp/tainted-format-string
  - exclude: cpp/toctou-race-condition
  - exclude: cpp/constant-comparison
