#!/bin/sh
#
# "$Id: pstoraster,v 1.1.2.2 2002/04/21 16:11:29 mike Exp $"
#
# CUPS filter script for Ghostscript.
#
# Copyright 2001-2002 by Easy Software Products.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

# Installation directories...
prefix=/usr
exec_prefix=${prefix}
bindir=${exec_prefix}/bin
datadir=${prefix}/share

# Set the library/font path...
GS_FONTPATH="$CUPS_FONTPATH"
export GS_FONTPATH

# Options we use with Ghostscript...
gsopts="-dQUIET -dDEBUG -dPARANOIDSAFER -dNOPAUSE -dBATCH -sDEVICE=cups -sstdout=%stderr"

# See if we have a profile=n,n,n,n,n,n,n,n,n,n,n option...
profile=""
for option in $5; do
    case $option in
        profile=*)
	    profile="-scupsProfile=`echo $option | awk -F= '{print $2}'`"
	    ;;
    esac
done

# Now run Ghostscript...
$bindir/gs $gsopts -sOUTPUTFILE="%stdout" $profile $6

#
# End of "$Id: pstoraster,v 1.1.2.2 2002/04/21 16:11:29 mike Exp $".
#
