#!/bin/sh -x
#
# Test script for making RPMs...
#

# Make sure we are running in the right directory...
if test ! -f scripts/makerpm; then
        echo "Run this script from the top-level CUPS source directory, e.g.:"
        echo ""
        echo "    scripts/makerpm [rpmbuild options]"
        echo ""
        exit 1
fi

# Strip command-line arguments so we don't create a release tag...
args="$*"
shift $#

# Get a snapshot of the current source...
. scripts/makesrcdist

# Build the RPM...
echo Building rpm...
#rm -f /usr/src/redhat/RPMS/i386/cups*.rpm
#rm -f /usr/src/redhat/SRPMS/cups*.rpm
rpmbuild -ta $args cups-${fileversion}-source.tar.gz
