#!/bin/sh
#
# Check .po files to see if there are untranslated or fuzzy strings.
#
# Usage: checkpo filename.po [ ... filenameN.po]
#

if test $# = 1; then
	echo Usage: checkpo filename.po ... filenameN.po
	exit 1
fi

echo "Catalog               Untrans  Fuzzy"
echo "--------------------  -------  -------"

for file in $*; do
	untranslated=`msgattrib --untranslated $file | grep 'msgid "..*"' | wc -l`
	fuzzy=`grep fuzzy $file | wc -l`

	printf "%-20.20s  %7d  %7d\n" $file $untranslated $fuzzy
done

