#!/bin/sh
#
# "$Id$"
#
# makesrcdist - make a source distribution of CUPS.
#

# Make sure we are running in the right directory...
if test ! -f tools/makesrcdist; then
        echo "Run this script from the top-level CUPS source directory, e.g.:"
        echo ""
        echo "    tools/makesrcdist $*"
        echo ""
        exit 1
fi

if test $# = 0; then
	echo Updating for snapshot...
	svn up
	rev=`svnversion . | sed -e '1,$s/[a-zA-Z]//g'`
	version="1.2svn"
	fileversion="1.2svn-r$rev"
	fileurl="ftp://ftp.easysw.com/pub/cups/test/cups-$fileversion-source.tar.bz2"
	url="."
else
	echo Creating tag for release...
	rev="1"
	version=$1
	fileversion=$1
	fileurl="ftp://ftp.easysw.com/pub/cups/$version/cups-$fileversion-source.tar.bz2"
	url="https://svn.easysw.com/public/cups/tags/release-$version"

	svn copy https://svn.easysw.com/public/cups/trunk "$url" \
		-m "Tag $version" || exit 1
fi

echo Exporting $fileversion...
rm -rf /tmp/cups-$version
svn export $url /tmp/cups-$version

echo Updating version information...
cd /tmp/cups-$version/config-scripts

sed -e '1,$s/^CUPS_VERSION=.*/CUPS_VERSION='$version'/' \
	<cups-common.m4 >cups-common.m4.new
mv cups-common.m4.new cups-common.m4
cd ..
fileurl=`echo $fileurl | sed -e '1,$s/\\//\\\\\\//g'`
sed -e '1,$s/@CUPS_VERSION@/'$version'/' \
	-e '1,$s/^Release:.*/Release: '$rev'/' \
	-e '1,$s/^Source:.*/Source: '$fileurl'/' \
	<packaging/cups.spec.in >packaging/cups.spec

echo Configuring...
autoconf -f
rm -rf autom4te*.cache
rm -rf standards
rm -rf tools
cd ..

echo -n Archiving...gz
tar czf cups-$version-r$rev-source.tar.gz cups-$version
echo -n ...bz2
tar cjf cups-$version-r$rev-source.tar.bz2 cups-$version
echo "..."

echo "Done!"

#
# End of "$Id$".
#
