#!/bin/sh
# Make sure we are running in the right directory...
if test ! -f tools/testosx; then
	echo "Run this script from the top-level CUPS source directory, e.g.:"
	echo ""
	echo "    tools/testosx"
	echo ""
	exit 1
fi

# Update the current working copy...
svn up
rev=`svnversion . | sed -e '1,$s/[a-zA-Z]//g'`

# Make everything...
make all

# Setup an install directory...
user=`whoami`
topdir=`pwd`
pkgdir="/tmp/cups-$user"

echo Building package using temp directory $pkgdir...
rm -rf $pkgdir
mkdir -p $pkgdir/Package
mkdir -p $pkgdir/Resources

# Install CUPS into the Package directory...
#make INSTALL=$topdir/install-sh BUILDROOT=$pkgdir/Package install
make BUILDROOT=$pkgdir/Package install

# Install resource files into the Resources directory...
echo Installing resource files...
cp LICENSE.rtf $pkgdir/Resources/ReadMe.rtf
cp WELCOME.rtf $pkgdir/Resources/Welcome.rtf
cp doc/images/cups-installer.tif $pkgdir/Resources/background.tif

cat >$pkgdir/Resources/preflight <<EOF
#!/bin/sh
killall cupsd
EOF
chmod 755 $pkgdir/Resources/preflight

cat >$pkgdir/Resources/postflight <<EOF
#!/bin/sh
/usr/sbin/cupsd
EOF
chmod 755 $pkgdir/Resources/postflight

# Tag the current revision in the plist and web interface files...
sed -e '1,$s/@CUPS_VERSION@/1.2svn-r'$rev'/g' \
	-e '1,$s/@CUPS_RELEASE@/1.2.'$rev'/g' \
	<cups-desc.plist.in >cups-desc.plist
sed -e '1,$s/@CUPS_VERSION@/1.2svn-r'$rev'/g' \
	-e '1,$s/@CUPS_RELEASE@/1.2.'$rev'/g' \
	<cups-info.plist.in >cups-info.plist
sed -e '1,$s/@CUPS_VERSION@/1.2svn-r'$rev'/g' <doc/index.html.in >doc/index.html

# Figure out where PackageMaker is installled...
if test -d /Developer/Applications/Utilities/PackageMaker.app; then
	PackageMaker=/Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker
else
	PackageMaker=/Developer/Applications/PackageMaker.app/Contents/MacOS/PackageMaker
fi

# Create the package...
echo Creating MacOS X package...
rm -rf cups.pkg
echo $PackageMaker -build -v -p cups.pkg \
	-f $pkgdir/Package \
	-r $pkgdir/Resources \
	-d cups-desc.plist \
	-i cups-info.plist
$PackageMaker -build -v -p cups.pkg \
	-f $pkgdir/Package \
	-r $pkgdir/Resources \
	-d cups-desc.plist \
	-i cups-info.plist

# Create a disk image...
echo Creating MacOS X disk image...
hdiutil create -ov -srcfolder cups.pkg cups-1.2svn-r$rev.dmg

# Cleanup temp files...
echo Removing temporary files...
rm -rf $pkgdir
